### ISSUE TITLE
Bad name of the method isRelativeUrl

### ISSUE THREAD

**Issue by or-else** [braintree/sanitize-url#16]
https://github.com/braintree/sanitize-url/blob/a396c4c532ac17efd7ec96f1c48855f6e633afd8/index.js#L9

It's a bad practice to call something `isAbc` when in reality it does not check for `Abc`:

```javascript
var relativeFirstCharacters = ['.', '/']
function isRelativeUrl(url) {
  return relativeFirstCharacters.indexOf(url[0]) > -1;
}
isRelativeUrl('//malicious-host.example.com/powned.html');
--> true
```
<a href="//example.com/">click me!</a>

The bad naming is not a bug per se but it's a bad practice. Someone may copy this method from your package thinking that the method ensures that the URL is relative.

**Comment by crookedneighbor** [comment]
Would you like to open a pull request?

**Comment by or-else** [comment]
No, not really. Thanks for offering though.
