### ISSUE TITLE
Protocol-less network paths return 'about:blank'

### ISSUE THREAD

**Issue by chawes13** [braintree/sanitize-url#18]
When sanitizing a user's input for their website, I was expecting a protocol-less url without XSS vectors to return the user's input.

**Expected**:
```js
import { sanitizeUrl } from '@braintree/sanitize-url'

sanitizeUrl('www.google.com') // www.google.com
sanitizeUrl('google.com') // google.com
```
**Actual**:
```js
import { sanitizeUrl } from '@braintree/sanitize-url'

sanitizeUrl('www.google.com') // about:blank
sanitizeUrl('google.com') // about:blank
```
The documentation via the tests seems to suggest that a [protocol-less url](https://github.com/braintree/sanitize-url/blob/707358e29e12059b2be0f007b88226933e2b7e76/test/test.js#L75) should be acceptable. However, the [isUrlWithoutProtocol](https://github.com/braintree/sanitize-url/blob/707358e29e12059b2be0f007b88226933e2b7e76/index.js#L8) helper requires a relative path (i.e., '.' or '/').

**Comment by crookedneighbor** [comment]
@chawes13 This module is used primarily with the Braintree SDKs, so it was built to accommodate the kinds of urls that pass through them (web urls with protocols, as well as deep link mobile urls).

If you'd like to open a PR to account for the behavior you pointed out, we're happy to review it, but it meets the needs of the Braintree SDKs as is, so I don't see us changing it ourselves in the near future. (too many other more important tasks to handle right now)

**Comment by chawes13** [comment]
That's fair! Appreciate the quick response. I'll likely just fork for our immediate needs and then submit a PR in a few weeks if I can settle on an approach.

**Comment by crookedneighbor** [comment]
:+1:

I'm going to close this issue for now, since there's nothing actionable for the Braintree team, but definitely open a PR. We're happy to look at it.
