### ISSUE TITLE
Typescript declaration file confusion

### ISSUE THREAD

**Issue by jf-t** [braintree/sanitize-url#25]
Running a production build of our Typescript application is now showing me:

```
Could not find a declaration file for module '@braintree/sanitize-url'. '/usr/src/app/node_modules/@braintree/sanitize-url/dist/index.js' implicitly has an 'any' type.
```

In the console log and I am unable to run a build. I originally had the DefinitelyTyped package installed, which was recently overwritten as you are including a `dist` folder.

From what I see, node is trying to read `index.js` file for some reason, when it should be reading `index.d.ts`? but I am not sure a way around this. I have version 4.1.0 installed, and it seemingly works for me locally, but only fails when running a production build.

**Comment by crookedneighbor** [comment]
Can you make a sample repo that reproduces the problem?

**Comment by jf-t** [comment]
Sorry I don't have time currently to do that - I forced my package back to version 4.0.1 and the issue went away so I am sure this is the problem. When I have a few hours to spend I will make a sample repo and try to reproduce it that way, sorry about that.

**Comment by crookedneighbor** [comment]
I was able to reproduce locally. Looking into fixing it up.

**Comment by crookedneighbor** [comment]
Fixed in v4.1.1

**Comment by jf-t** [comment]
Thank you! @crookedneighbor I will try our site to use 4.1.1 tomorrow.

**Comment by jf-t** [comment]
This fixed it :+1:
