### ISSUE TITLE
Sanitize VBScript

### ISSUE THREAD

**Issue by vicnicius** [braintree/sanitize-url#26]
VBScript is deprecated, and IE11 has it [disabled by default since July 2019](https://blogs.windows.com/msedgedev/2019/08/02/update-disabling-vbscript-internet-explorer-windows-7-8/). Yet, users with outdated versions of IE or Windows could potentially be victims of VBScript based XSS attacks.
I'm not sure what the current browser support for this lib is, but regardless, it looks like disallowing VBScript as a protocol could be easily achieved.
I'd be happy to make a PR in case you're interested in also disallowing it.

**Comment by crookedneighbor** [comment]
Feel free to open a PR.
