### ISSUE TITLE
Should sanitize-url replace zero width characters?

### ISSUE THREAD

**Issue by jackw** [braintree/sanitize-url#35]
Having updated to v5.0.1 I've noticed that `sanitize-url` is no longer replacing zero width characters. 

Is this by design or a regression caused by changes made in v5.0.1?

Please see https://github.com/grafana/grafana/issues/34528 for an example.

**Comment by crookedneighbor** [comment]
Yeah, I believe that's a regression. We'll get it fixed.

**Comment by jackw** [comment]
Amazing! Thanks so much @crookedneighbor

**Comment by crookedneighbor** [comment]
This is out in v5.0.2
