### ISSUE TITLE
Interest in type definitions?

### ISSUE THREAD

**Issue by bufke** [braintree/sanitize-url#4]
This module is so small - it would be trivial to add typescript type definitions. I'd be happy to submit them. Basically:

```
declare module "@braintree/sanitize-url" {
  export function sanitizeUrl(url: string): string;
};
```

**Comment by crookedneighbor** [comment]
We're not interested in adding them, but feel free to submit a PR to https://github.com/DefinitelyTyped/DefinitelyTyped yourself if you wish.

**Comment by krzysztofzuraw** [comment]
Hi 👋🏻 I've just added them: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43343

**Comment by crookedneighbor** [comment]
FYI, this module is now written in typescript.

PR to remove the types from DT: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46109
