### ISSUE TITLE
Enable private vulnerability reporting

### ISSUE THREAD

**Issue by Panya** [braintree/sanitize-url#48]
Hi there.

I've found a security issue in your library. Can you enable the newly deployed feature of GitHub (https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository), so I can share the details?

I also reported it to https://huntr.dev. The issue should be accessible to you by this URL: https://huntr.dev/bounties/8879054f-80a7-457c-bf17-a4ecd4b73a28/

**Comment by hollabaq86** [comment]
👋 We take security vulnerabilities very seriously and appreciate your help notifying us of vulnerabilities in a responsible manner. If you encounter any security vulnerabilities, please submit them to [PayPal’s Bug Bounty Program](https://www.paypal.com/bugbounty). If you have any questions, please reach out to [ppbugbounty@paypal.com](mailto:ppbugbounty@paypal.com).
