### ISSUE TITLE
return str.replace(htmlEntitiesRegex, (match, dec :  str.replace is not a function

### ISSUE THREAD

**Issue by DNeelanshi** [braintree/sanitize-url#54]
Null check is needed on str as its throwing error that str.replace is not a function

**Comment by oscarleonnogales** [comment]
HI @DNeelanshi,

Great observation, I see what you mean. Please feel free to submit a PR with this change if you'd like to contribute!

For internal tracking, DTBTSDK-2818

**Comment by DNeelanshi** [comment]
Thank you @oscarleonnogales  for your response , I will try to contribute to fix this issue.

**Comment by DNeelanshi** [comment]
please review PR https://github.com/braintree/sanitize-url/pull/56

**Comment by oscarleonnogales** [comment]
Thank you for starting the PR @DNeelanshi, I went ahead and did a few other changes along with your code and added you as a co-author for the final commit.

Closing this issue now as the PR has been merged and will be out in the next release.
