### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by jameswragg** [braintree/sanitize-url#60]
#57 included exporting `BLANK_URL` - this is useful for tests & would be great to get published to npm.

Can we get a new release please?

**Comment by hollabaq86** [comment]
👋 @jameswragg thanks for reaching out! Yeah this release slipped our minds, we'll get a release out soon.

**Comment by hollabaq86** [comment]
we just released 6.0.3. Thanks again for reaching out!
